// source: urltoimage/urltoimage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.liburltoimage.PDFOptions');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.liburltoimage.PDFMargin');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.liburltoimage.PDFOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.liburltoimage.PDFOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.liburltoimage.PDFOptions.displayName = 'proto.liburltoimage.PDFOptions';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.liburltoimage.PDFOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.liburltoimage.PDFOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.liburltoimage.PDFOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.liburltoimage.PDFOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    format: jspb.Message.getFieldWithDefault(msg, 1, ""),
    displayheaderfooter: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    footertemplate: jspb.Message.getFieldWithDefault(msg, 3, ""),
    headertemplate: jspb.Message.getFieldWithDefault(msg, 4, ""),
    height: jspb.Message.getFieldWithDefault(msg, 5, ""),
    width: jspb.Message.getFieldWithDefault(msg, 6, ""),
    landscape: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    omitbackground: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    pageranges: jspb.Message.getFieldWithDefault(msg, 9, ""),
    margin: (f = msg.getMargin()) && proto.liburltoimage.PDFMargin.toObject(includeInstance, f),
    printbackground: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    prefercsspagesize: jspb.Message.getBooleanFieldWithDefault(msg, 12, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.liburltoimage.PDFOptions}
 */
proto.liburltoimage.PDFOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.liburltoimage.PDFOptions;
  return proto.liburltoimage.PDFOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.liburltoimage.PDFOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.liburltoimage.PDFOptions}
 */
proto.liburltoimage.PDFOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFormat(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDisplayheaderfooter(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFootertemplate(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeadertemplate(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeight(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setWidth(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLandscape(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOmitbackground(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageranges(value);
      break;
    case 10:
      var value = new proto.liburltoimage.PDFMargin;
      reader.readMessage(value,proto.liburltoimage.PDFMargin.deserializeBinaryFromReader);
      msg.setMargin(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPrintbackground(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPrefercsspagesize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.liburltoimage.PDFOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.liburltoimage.PDFOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.liburltoimage.PDFOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.liburltoimage.PDFOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFormat();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDisplayheaderfooter();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getFootertemplate();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHeadertemplate();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHeight();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getWidth();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLandscape();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getOmitbackground();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getPageranges();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getMargin();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.liburltoimage.PDFMargin.serializeBinaryToWriter
    );
  }
  f = message.getPrintbackground();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getPrefercsspagesize();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
};


/**
 * optional string format = 1;
 * @return {string}
 */
proto.liburltoimage.PDFOptions.prototype.getFormat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setFormat = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool displayHeaderFooter = 2;
 * @return {boolean}
 */
proto.liburltoimage.PDFOptions.prototype.getDisplayheaderfooter = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setDisplayheaderfooter = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string footerTemplate = 3;
 * @return {string}
 */
proto.liburltoimage.PDFOptions.prototype.getFootertemplate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setFootertemplate = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string headerTemplate = 4;
 * @return {string}
 */
proto.liburltoimage.PDFOptions.prototype.getHeadertemplate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setHeadertemplate = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string height = 5;
 * @return {string}
 */
proto.liburltoimage.PDFOptions.prototype.getHeight = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setHeight = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string width = 6;
 * @return {string}
 */
proto.liburltoimage.PDFOptions.prototype.getWidth = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setWidth = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bool landscape = 7;
 * @return {boolean}
 */
proto.liburltoimage.PDFOptions.prototype.getLandscape = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setLandscape = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool omitBackground = 8;
 * @return {boolean}
 */
proto.liburltoimage.PDFOptions.prototype.getOmitbackground = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setOmitbackground = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional string pageRanges = 9;
 * @return {string}
 */
proto.liburltoimage.PDFOptions.prototype.getPageranges = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setPageranges = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional PDFMargin margin = 10;
 * @return {?proto.liburltoimage.PDFMargin}
 */
proto.liburltoimage.PDFOptions.prototype.getMargin = function() {
  return /** @type{?proto.liburltoimage.PDFMargin} */ (
    jspb.Message.getWrapperField(this, proto.liburltoimage.PDFMargin, 10));
};


/**
 * @param {?proto.liburltoimage.PDFMargin|undefined} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
*/
proto.liburltoimage.PDFOptions.prototype.setMargin = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.clearMargin = function() {
  return this.setMargin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.liburltoimage.PDFOptions.prototype.hasMargin = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool printBackground = 11;
 * @return {boolean}
 */
proto.liburltoimage.PDFOptions.prototype.getPrintbackground = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setPrintbackground = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool preferCSSPageSize = 12;
 * @return {boolean}
 */
proto.liburltoimage.PDFOptions.prototype.getPrefercsspagesize = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.liburltoimage.PDFOptions} returns this
 */
proto.liburltoimage.PDFOptions.prototype.setPrefercsspagesize = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


