// source: urltoimage/urltoimage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.liburltoimage.Request');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.liburltoimage.PDFOptions');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.liburltoimage.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.liburltoimage.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.liburltoimage.Request.displayName = 'proto.liburltoimage.Request';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.liburltoimage.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.liburltoimage.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.liburltoimage.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.liburltoimage.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    size: jspb.Message.getFieldWithDefault(msg, 2, ""),
    type: jspb.Message.getFieldWithDefault(msg, 3, ""),
    quality: jspb.Message.getFieldWithDefault(msg, 4, 0),
    transparent: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    pdfoptions: (f = msg.getPdfoptions()) && proto.liburltoimage.PDFOptions.toObject(includeInstance, f),
    capturebeyondviewport: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.liburltoimage.Request}
 */
proto.liburltoimage.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.liburltoimage.Request;
  return proto.liburltoimage.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.liburltoimage.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.liburltoimage.Request}
 */
proto.liburltoimage.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSize(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuality(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTransparent(value);
      break;
    case 6:
      var value = new proto.liburltoimage.PDFOptions;
      reader.readMessage(value,proto.liburltoimage.PDFOptions.deserializeBinaryFromReader);
      msg.setPdfoptions(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCapturebeyondviewport(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.liburltoimage.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.liburltoimage.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.liburltoimage.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.liburltoimage.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSize();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getQuality();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getTransparent();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getPdfoptions();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.liburltoimage.PDFOptions.serializeBinaryToWriter
    );
  }
  f = message.getCapturebeyondviewport();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.liburltoimage.Request.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.Request} returns this
 */
proto.liburltoimage.Request.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string size = 2;
 * @return {string}
 */
proto.liburltoimage.Request.prototype.getSize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.Request} returns this
 */
proto.liburltoimage.Request.prototype.setSize = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string type = 3;
 * @return {string}
 */
proto.liburltoimage.Request.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.liburltoimage.Request} returns this
 */
proto.liburltoimage.Request.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 quality = 4;
 * @return {number}
 */
proto.liburltoimage.Request.prototype.getQuality = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.liburltoimage.Request} returns this
 */
proto.liburltoimage.Request.prototype.setQuality = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bool transparent = 5;
 * @return {boolean}
 */
proto.liburltoimage.Request.prototype.getTransparent = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.liburltoimage.Request} returns this
 */
proto.liburltoimage.Request.prototype.setTransparent = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional PDFOptions pdfoptions = 6;
 * @return {?proto.liburltoimage.PDFOptions}
 */
proto.liburltoimage.Request.prototype.getPdfoptions = function() {
  return /** @type{?proto.liburltoimage.PDFOptions} */ (
    jspb.Message.getWrapperField(this, proto.liburltoimage.PDFOptions, 6));
};


/**
 * @param {?proto.liburltoimage.PDFOptions|undefined} value
 * @return {!proto.liburltoimage.Request} returns this
*/
proto.liburltoimage.Request.prototype.setPdfoptions = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.liburltoimage.Request} returns this
 */
proto.liburltoimage.Request.prototype.clearPdfoptions = function() {
  return this.setPdfoptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.liburltoimage.Request.prototype.hasPdfoptions = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool captureBeyondViewport = 7;
 * @return {boolean}
 */
proto.liburltoimage.Request.prototype.getCapturebeyondviewport = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.liburltoimage.Request} returns this
 */
proto.liburltoimage.Request.prototype.setCapturebeyondviewport = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


