# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: urltoimage/urltoimage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1burltoimage/urltoimage.proto\x12\rliburltoimage\"\xa6\x01\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07quality\x18\x04 \x01(\x05\x12\x13\n\x0btransparent\x18\x05 \x01(\x08\x12-\n\npdfoptions\x18\x06 \x01(\x0b\x32\x19.liburltoimage.PDFOptions\x12\x1d\n\x15\x63\x61ptureBeyondViewport\x18\x07 \x01(\x08\"\xa5\x02\n\nPDFOptions\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12\x1b\n\x13\x64isplayHeaderFooter\x18\x02 \x01(\x08\x12\x16\n\x0e\x66ooterTemplate\x18\x03 \x01(\t\x12\x16\n\x0eheaderTemplate\x18\x04 \x01(\t\x12\x0e\n\x06height\x18\x05 \x01(\t\x12\r\n\x05width\x18\x06 \x01(\t\x12\x11\n\tlandscape\x18\x07 \x01(\x08\x12\x16\n\x0eomitBackground\x18\x08 \x01(\x08\x12\x12\n\npageRanges\x18\t \x01(\t\x12(\n\x06margin\x18\n \x01(\x0b\x32\x18.liburltoimage.PDFMargin\x12\x17\n\x0fprintBackground\x18\x0b \x01(\x08\x12\x19\n\x11preferCSSPageSize\x18\x0c \x01(\x08\"E\n\tPDFMargin\x12\x0e\n\x06\x62ottom\x18\x01 \x01(\t\x12\x0c\n\x04left\x18\x02 \x01(\t\x12\r\n\x05right\x18\x03 \x01(\t\x12\x0b\n\x03top\x18\x04 \x01(\t\",\n\x0b\x46ileContent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"T\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12)\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x1a.liburltoimage.FileContent2J\n\nUrltoimage\x12<\n\x07\x43onvert\x12\x16.liburltoimage.Request\x1a\x17.liburltoimage.Response\"\x00\x42\x19Z\x17mxiqi.com/liburltoimageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'urltoimage.urltoimage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027mxiqi.com/liburltoimage'
  _REQUEST._serialized_start=47
  _REQUEST._serialized_end=213
  _PDFOPTIONS._serialized_start=216
  _PDFOPTIONS._serialized_end=509
  _PDFMARGIN._serialized_start=511
  _PDFMARGIN._serialized_end=580
  _FILECONTENT._serialized_start=582
  _FILECONTENT._serialized_end=626
  _RESPONSE._serialized_start=628
  _RESPONSE._serialized_end=712
  _URLTOIMAGE._serialized_start=714
  _URLTOIMAGE._serialized_end=788
# @@protoc_insertion_point(module_scope)
