<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: urltoimage/urltoimage.proto

namespace Liburltoimage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>liburltoimage.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     *文件名,可选
     *
     * Generated from protobuf field <code>string url = 1;</code>
     */
    private $url = '';
    /**
     *要转换成的类型,pdf,png/jpg
     *
     * Generated from protobuf field <code>string size = 2;</code>
     */
    private $size = '';
    /**
     * Generated from protobuf field <code>string type = 3;</code>
     */
    private $type = '';
    /**
     * Generated from protobuf field <code>int32 quality = 4;</code>
     */
    private $quality = 0;
    /**
     *是否透明
     *
     * Generated from protobuf field <code>bool transparent = 5;</code>
     */
    private $transparent = false;
    /**
     * Generated from protobuf field <code>.liburltoimage.PDFOptions pdfoptions = 6;</code>
     */
    private $pdfoptions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *          文件名,可选
     *     @type string $size
     *          要转换成的类型,pdf,png/jpg
     *     @type string $type
     *     @type int $quality
     *     @type bool $transparent
     *          是否透明
     *     @type \Liburltoimage\PDFOptions $pdfoptions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Urltoimage\Urltoimage::initOnce();
        parent::__construct($data);
    }

    /**
     *文件名,可选
     *
     * Generated from protobuf field <code>string url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     *文件名,可选
     *
     * Generated from protobuf field <code>string url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     *要转换成的类型,pdf,png/jpg
     *
     * Generated from protobuf field <code>string size = 2;</code>
     * @return string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     *要转换成的类型,pdf,png/jpg
     *
     * Generated from protobuf field <code>string size = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkString($var, True);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quality = 4;</code>
     * @return int
     */
    public function getQuality()
    {
        return $this->quality;
    }

    /**
     * Generated from protobuf field <code>int32 quality = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setQuality($var)
    {
        GPBUtil::checkInt32($var);
        $this->quality = $var;

        return $this;
    }

    /**
     *是否透明
     *
     * Generated from protobuf field <code>bool transparent = 5;</code>
     * @return bool
     */
    public function getTransparent()
    {
        return $this->transparent;
    }

    /**
     *是否透明
     *
     * Generated from protobuf field <code>bool transparent = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setTransparent($var)
    {
        GPBUtil::checkBool($var);
        $this->transparent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.liburltoimage.PDFOptions pdfoptions = 6;</code>
     * @return \Liburltoimage\PDFOptions
     */
    public function getPdfoptions()
    {
        return $this->pdfoptions;
    }

    /**
     * Generated from protobuf field <code>.liburltoimage.PDFOptions pdfoptions = 6;</code>
     * @param \Liburltoimage\PDFOptions $var
     * @return $this
     */
    public function setPdfoptions($var)
    {
        GPBUtil::checkMessage($var, \Liburltoimage\PDFOptions::class);
        $this->pdfoptions = $var;

        return $this;
    }

}

