<?php
# Generated by the protocol buffer compiler (hetao29/php-grpc-server-protobuf-plugin). DO NOT EDIT!
# source: urltoimage/urltoimage.proto

namespace Liburltoimage;


interface UrltoimageInterface
{
    // GRPC specific service name.
    public const NAME = "liburltoimage.Urltoimage";

    /**
    * @param Request $request
    * @return Response
    *
    * @throws \Exception
    */
    public function Convert(Request $request): Response;
}
