<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: urltoimage/urltoimage.proto

namespace GPBMetadata\Urltoimage;

class Urltoimage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af9020a1b75726c746f696d6167652f75726c746f696d6167652e70726f" .
            "746f120d6c696275726c746f696d61676522580a0752657175657374120b" .
            "0a0375726c180120012809120c0a0473697a65180220012809120c0a0474" .
            "797065180320012809120f0a077175616c69747918042001280512130a0b" .
            "7472616e73706172656e74180520012808222c0a0b46696c65436f6e7465" .
            "6e74120c0a046e616d65180120012809120f0a07636f6e74656e74180220" .
            "01280c22540a08526573706f6e7365120c0a04636f646518012001280512" .
            "0f0a076d65737361676518022001280912290a0566696c65731803200328" .
            "0b321a2e6c696275726c746f696d6167652e46696c65436f6e74656e7432" .
            "4a0a0a55726c746f696d616765123c0a07436f6e7665727412162e6c6962" .
            "75726c746f696d6167652e526571756573741a172e6c696275726c746f69" .
            "6d6167652e526573706f6e7365220042195a176d786971692e636f6d2f6c" .
            "696275726c746f696d616765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

