<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: urltoimage/urltoimage.proto

namespace GPBMetadata\Urltoimage;

class Urltoimage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4020a1b75726c746f696d6167652f75726c746f696d6167652e70726f" .
            "746f120d6c696275726c746f696d61676522430a0752657175657374120b" .
            "0a0375726c180120012809120c0a0473697a65180220012809120c0a0474" .
            "797065180320012809120f0a077175616c697479180420012805222c0a0b" .
            "46696c65436f6e74656e74120c0a046e616d65180120012809120f0a0763" .
            "6f6e74656e7418022001280c22540a08526573706f6e7365120c0a04636f" .
            "6465180120012805120f0a076d65737361676518022001280912290a0566" .
            "696c657318032003280b321a2e6c696275726c746f696d6167652e46696c" .
            "65436f6e74656e74324a0a0a55726c746f696d616765123c0a07436f6e76" .
            "65727412162e6c696275726c746f696d6167652e526571756573741a172e" .
            "6c696275726c746f696d6167652e526573706f6e7365220042195a176d78" .
            "6971692e636f6d2f6c696275726c746f696d616765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

