// Code generated by protoc-gen-go. DO NOT EDIT.
// source: urltoimage/urltoimage.proto

/*
Package liburltoimage is a generated protocol buffer package.

It is generated from these files:
	urltoimage/urltoimage.proto

It has these top-level messages:
	Request
	FileContent
	Response
*/
package liburltoimage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	// 文件名,可选
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// 要转换成的类型,pdf,png/jpg
	Size    string `protobuf:"bytes,2,opt,name=size" json:"size,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Quality int32  `protobuf:"varint,4,opt,name=quality" json:"quality,omitempty"`
	// 是否透明
	Transparent bool `protobuf:"varint,5,opt,name=transparent" json:"transparent,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Request) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *Request) GetTransparent() bool {
	if m != nil {
		return m.Transparent
	}
	return false
}

type FileContent struct {
	// 文件名
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// 二进制的文件内容
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *FileContent) Reset()                    { *m = FileContent{} }
func (m *FileContent) String() string            { return proto.CompactTextString(m) }
func (*FileContent) ProtoMessage()               {}
func (*FileContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FileContent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileContent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Response struct {
	Code    int32          `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Files   []*FileContent `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetFiles() []*FileContent {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "liburltoimage.Request")
	proto.RegisterType((*FileContent)(nil), "liburltoimage.FileContent")
	proto.RegisterType((*Response)(nil), "liburltoimage.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Urltoimage service

type UrltoimageClient interface {
	// Sends a greeting
	Convert(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type urltoimageClient struct {
	cc *grpc.ClientConn
}

func NewUrltoimageClient(cc *grpc.ClientConn) UrltoimageClient {
	return &urltoimageClient{cc}
}

func (c *urltoimageClient) Convert(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/liburltoimage.Urltoimage/Convert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Urltoimage service

type UrltoimageServer interface {
	// Sends a greeting
	Convert(context.Context, *Request) (*Response, error)
}

func RegisterUrltoimageServer(s *grpc.Server, srv UrltoimageServer) {
	s.RegisterService(&_Urltoimage_serviceDesc, srv)
}

func _Urltoimage_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrltoimageServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liburltoimage.Urltoimage/Convert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrltoimageServer).Convert(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Urltoimage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "liburltoimage.Urltoimage",
	HandlerType: (*UrltoimageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _Urltoimage_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "urltoimage/urltoimage.proto",
}

func init() { proto.RegisterFile("urltoimage/urltoimage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x46, 0x09, 0x69, 0x68, 0xb9, 0x80, 0x84, 0x3c, 0x50, 0x53, 0x96, 0x28, 0x53, 0xa6, 0x14,
	0x95, 0x11, 0x26, 0x2a, 0x31, 0x30, 0x5a, 0x62, 0x61, 0x73, 0xc3, 0x51, 0x19, 0x39, 0x76, 0x62,
	0x3b, 0x88, 0xb2, 0xf0, 0xd7, 0x91, 0x9d, 0x86, 0xb6, 0xb0, 0xbd, 0x7b, 0xb9, 0x3b, 0x7d, 0x39,
	0xc3, 0x75, 0x67, 0xa4, 0xd3, 0xa2, 0xe6, 0x6b, 0x9c, 0xef, 0xb0, 0x6c, 0x8c, 0x76, 0x9a, 0x9c,
	0x4b, 0xb1, 0xda, 0xc9, 0xfc, 0x1b, 0xc6, 0x0c, 0xdb, 0x0e, 0xad, 0x23, 0x17, 0x10, 0x77, 0x46,
	0xd2, 0x28, 0x8b, 0x8a, 0x53, 0xe6, 0x91, 0x10, 0x18, 0x59, 0xf1, 0x85, 0xf4, 0x38, 0xa8, 0xc0,
	0xde, 0xb9, 0x4d, 0x83, 0x34, 0xee, 0x9d, 0x67, 0x42, 0x61, 0xdc, 0x76, 0x5c, 0x0a, 0xb7, 0xa1,
	0xa3, 0x2c, 0x2a, 0x12, 0x36, 0x94, 0x24, 0x83, 0xd4, 0x19, 0xae, 0x6c, 0xc3, 0x0d, 0x2a, 0x47,
	0x93, 0x2c, 0x2a, 0x26, 0x6c, 0x5f, 0xe5, 0x77, 0x90, 0x3e, 0x0a, 0x89, 0x4b, 0xad, 0x1c, 0x2a,
	0xe7, 0xd7, 0x2b, 0x5e, 0xe3, 0x36, 0x45, 0x60, 0xbf, 0xbe, 0xea, 0x3f, 0x87, 0x24, 0x67, 0x6c,
	0x28, 0xf3, 0x77, 0x98, 0x30, 0xb4, 0x8d, 0x56, 0x36, 0x04, 0xab, 0xf4, 0x6b, 0x3f, 0x99, 0xb0,
	0xc0, 0x7e, 0xb2, 0x46, 0x6b, 0xf9, 0x7a, 0xf8, 0x87, 0xa1, 0x24, 0x37, 0x90, 0xbc, 0x09, 0x89,
	0x96, 0xc6, 0x59, 0x5c, 0xa4, 0x8b, 0x59, 0x79, 0x70, 0x96, 0x72, 0x2f, 0x12, 0xeb, 0x1b, 0x17,
	0x4f, 0x00, 0xcf, 0xbf, 0x0d, 0xe4, 0x1e, 0xc6, 0x4b, 0xad, 0x3e, 0xd0, 0x38, 0x72, 0xf9, 0x67,
	0x76, 0x7b, 0xcf, 0xd9, 0xf4, 0x9f, 0xef, 0x93, 0xe6, 0x47, 0x0f, 0x57, 0x2f, 0xd3, 0xfa, 0x53,
	0xb4, 0xa2, 0xac, 0x74, 0x3d, 0x3f, 0xe8, 0x5a, 0x9d, 0x84, 0x67, 0xba, 0xfd, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x74, 0xe5, 0x6c, 0x20, 0xc5, 0x01, 0x00, 0x00,
}
