// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: urltoimage/urltoimage.proto

#include "urltoimage/urltoimage.pb.h"
#include "urltoimage/urltoimage.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace liburltoimage {

static const char* Urltoimage_method_names[] = {
  "/liburltoimage.Urltoimage/Convert",
};

std::unique_ptr< Urltoimage::Stub> Urltoimage::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Urltoimage::Stub> stub(new Urltoimage::Stub(channel, options));
  return stub;
}

Urltoimage::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Convert_(Urltoimage_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Urltoimage::Stub::Convert(::grpc::ClientContext* context, const ::liburltoimage::Request& request, ::liburltoimage::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::liburltoimage::Request, ::liburltoimage::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Convert_, context, request, response);
}

void Urltoimage::Stub::async::Convert(::grpc::ClientContext* context, const ::liburltoimage::Request* request, ::liburltoimage::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::liburltoimage::Request, ::liburltoimage::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Convert_, context, request, response, std::move(f));
}

void Urltoimage::Stub::async::Convert(::grpc::ClientContext* context, const ::liburltoimage::Request* request, ::liburltoimage::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Convert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::liburltoimage::Response>* Urltoimage::Stub::PrepareAsyncConvertRaw(::grpc::ClientContext* context, const ::liburltoimage::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::liburltoimage::Response, ::liburltoimage::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Convert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::liburltoimage::Response>* Urltoimage::Stub::AsyncConvertRaw(::grpc::ClientContext* context, const ::liburltoimage::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConvertRaw(context, request, cq);
  result->StartCall();
  return result;
}

Urltoimage::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Urltoimage_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Urltoimage::Service, ::liburltoimage::Request, ::liburltoimage::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Urltoimage::Service* service,
             ::grpc::ServerContext* ctx,
             const ::liburltoimage::Request* req,
             ::liburltoimage::Response* resp) {
               return service->Convert(ctx, req, resp);
             }, this)));
}

Urltoimage::Service::~Service() {
}

::grpc::Status Urltoimage::Service::Convert(::grpc::ServerContext* context, const ::liburltoimage::Request* request, ::liburltoimage::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace liburltoimage

